import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cookieToInitialState } from "@wagmi/core";
import { headers } from "next/headers";
import { Header } from "./_components/header";
import { wagmiHttpConfig } from "./_config/wagmi";
import { RootProviders } from "./_context/root-providers";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const initialWagmiState = cookieToInitialState(
		wagmiHttpConfig,
		(await headers()).get("cookie"),
	);

	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<RootProviders initialWagmiState={initialWagmiState}>
					<Header />
					{children}
				</RootProviders>
			</body>
		</html>
	);
}
